// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VakifPayPos.Data;

#nullable disable

namespace VakifPayPos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VakifPayPos.Models.Customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customerID"));

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("businessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("customerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("longitute")
                        .HasColumnType("numeric");

                    b.Property<string>("managerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("managerTCKN")
                        .HasColumnType("bigint");

                    b.Property<string>("monthlySalary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("taxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("taxOffice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("webURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("customerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VakifPayPos.Models.CustomerDocument", b =>
                {
                    b.Property<int>("documentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("documentId"));

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("customerId")
                        .HasColumnType("integer");

                    b.Property<string>("documentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("documentId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerDocuments");
                });

            modelBuilder.Entity("VakifPayPos.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("orderId"));

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("customerId")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("totalAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("orderId");

                    b.HasIndex("customerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VakifPayPos.Models.OrderItem", b =>
                {
                    b.Property<int>("orderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("orderItemId"));

                    b.Property<decimal>("commisionRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("orderId")
                        .HasColumnType("integer");

                    b.Property<int>("productId")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("unitPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("orderItemId");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VakifPayPos.Models.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("paymentId"));

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cardExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cardHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("orderId")
                        .HasColumnType("integer");

                    b.HasKey("paymentId");

                    b.HasIndex("orderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VakifPayPos.Models.Pos", b =>
                {
                    b.Property<int>("posID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("posID"));

                    b.Property<decimal>("commisionRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isPurchase")
                        .HasColumnType("boolean");

                    b.Property<string>("posName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("posType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string>("priceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("valorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("posID");

                    b.ToTable("Pos");
                });

            modelBuilder.Entity("VakifPayPos.Models.CustomerDocument", b =>
                {
                    b.HasOne("VakifPayPos.Models.Customer", "Customer")
                        .WithMany("CustomerDocuments")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VakifPayPos.Models.Order", b =>
                {
                    b.HasOne("VakifPayPos.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VakifPayPos.Models.OrderItem", b =>
                {
                    b.HasOne("VakifPayPos.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VakifPayPos.Models.Pos", "Pos")
                        .WithMany("OrderItems")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Pos");
                });

            modelBuilder.Entity("VakifPayPos.Models.Payment", b =>
                {
                    b.HasOne("VakifPayPos.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VakifPayPos.Models.Customer", b =>
                {
                    b.Navigation("CustomerDocuments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("VakifPayPos.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VakifPayPos.Models.Pos", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
